"""Parses Claude's XML PRD response into a structured dict and markdown."""
import re


def parse_prd_response(raw: str) -> dict:
    def get(tag: str) -> str:
        m = re.search(rf"<{tag}>(.*?)</{tag}>", raw, re.DOTALL)
        return m.group(1).strip() if m else ""

    def get_all(tag: str) -> list[str]:
        return [m.strip() for m in re.findall(rf"<{tag}>(.*?)</{tag}>", raw, re.DOTALL)]

    tasks = []
    for task_xml in get_all("task"):
        def _get(t: str, x: str = task_xml) -> str:
            m = re.search(rf"<{t}>(.*?)</{t}>", x, re.DOTALL)
            return m.group(1).strip() if m else ""
        tasks.append({
            "title": _get("title"),
            "description": _get("description"),
            "estimate": _get("estimate") or "M",
        })

    return {
        "problem": get("problem"),
        "problem_quotes": get_all("quote"),
        "proposed_feature": get("proposed_feature"),
        "why_worth_building": get("why_worth_building"),
        "goals": get_all("goal"),
        "non_goals": get_all("non_goal"),
        "user_stories": get_all("story"),
        "what_needs_to_change": {
            "ui": get("ui"),
            "data_model": get("data_model"),
            "workflows": get("workflows"),
        },
        "engineering_tasks": tasks,
        "edge_cases": get_all("case"),
        "analytics_events": get_all("event"),
        "open_questions": get_all("question"),
    }


def prd_to_markdown(brief: dict) -> str:
    quotes_md = "\n".join([f'> "{q}"' for q in brief.get("problem_quotes", [])])
    goals_md = "\n".join([f"- {g}" for g in brief.get("goals", [])])
    non_goals_md = "\n".join([f"- {g}" for g in brief.get("non_goals", [])])
    stories_md = "\n".join([f"- {s}" for s in brief.get("user_stories", [])])
    wtc = brief.get("what_needs_to_change", {})
    tasks_md = "\n".join([
        f"- **{t['title']}** `{t['estimate']}`\n  {t['description']}"
        for t in brief.get("engineering_tasks", [])
    ])
    edge_cases_md = "\n".join([f"- {c}" for c in brief.get("edge_cases", [])])
    events_md = "\n".join([f"- {e}" for e in brief.get("analytics_events", [])])
    questions_md = "\n".join([f"- {q}" for q in brief.get("open_questions", [])])

    return f"""# PRD

## Problem
{brief.get('problem', '')}

{quotes_md}

## Proposed Feature
{brief.get('proposed_feature', '')}

## Why It's Worth Building
{brief.get('why_worth_building', '')}

## Goals
{goals_md}

## Non-Goals
{non_goals_md}

## User Stories
{stories_md}

## What Needs to Change

**UI Changes**
{wtc.get('ui', '')}

**Data Model**
{wtc.get('data_model', '')}

**Workflows**
{wtc.get('workflows', '')}

## Engineering Tasks
{tasks_md}

## Edge Cases
{edge_cases_md}

## Analytics Events
{events_md}

## Open Questions
{questions_md}

---
*Generated by PMRead · pmread.rohanyeole.com*
"""
