import re
from fpdf import FPDF


# ── colours ────────────────────────────────
PURPLE = (127, 119, 221)
GREEN  = (29,  158, 117)
GRAY   = (100, 100, 100)
LIGHT  = (248, 247, 255)
WHITE  = (255, 255, 255)


def _safe(text: str) -> str:
    """Replace common Unicode chars with latin-1 equivalents for core fonts."""
    return (
        text
        .replace("\u2013", "-").replace("\u2014", "--")
        .replace("\u2018", "'").replace("\u2019", "'")
        .replace("\u201c", '"').replace("\u201d", '"')
        .replace("\u2022", "-").replace("\u2026", "...")
        .replace("\u00a0", " ")
        # arrows
        .replace("\u2192", "->").replace("\u2190", "<-")
        .replace("\u2194", "<->").replace("\u21d2", "=>")
        .replace("\u2794", "->").replace("\u27a1", "->")
        # math / comparison
        .replace("\u2265", ">=").replace("\u2264", "<=")
        .replace("\u2260", "!=").replace("\u00d7", "x")
        .replace("\u00f7", "/").replace("\u00b1", "+/-")
        # misc
        .replace("\u2713", "v").replace("\u2717", "x")
        .replace("\u2605", "*").replace("\u2606", "*")
        .replace("\u00ae", "(R)").replace("\u2122", "(TM)")
        .encode("latin-1", errors="replace").decode("latin-1")
    )


class PRDPdf(FPDF):
    def header(self):
        pass  # custom header drawn per page via set_title_header

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GRAY)
        self.cell(0, 6, "Generated by PMRead · pmread.rohanyeole.com", align="C")

    # ── helpers ────────────────────────────
    def section_title(self, label: str):
        self.ln(5)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*PURPLE)
        self.cell(0, 7, label.upper(), ln=True)
        self.set_draw_color(*PURPLE)
        self.set_line_width(0.3)
        self.line(self.get_x(), self.get_y(), self.get_x() + self.epw, self.get_y())
        self.ln(2)

    def body_text(self, text: str, indent: float = 0):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(26, 26, 26)
        if indent:
            self.set_x(self.l_margin + indent)
        self.multi_cell(self.epw - indent, 5.5, _safe(text))
        self.ln(1)

    def quote_block(self, text: str):
        self.set_draw_color(*PURPLE)
        self.set_line_width(0.8)
        y = self.get_y()
        self.line(self.l_margin + 2, y, self.l_margin + 2, y + 16)
        self.set_font("Helvetica", "I", 9.5)
        self.set_text_color(*GRAY)
        self.set_x(self.l_margin + 6)
        self.multi_cell(self.epw - 6, 5, _safe(f'"{text}"'))
        self.ln(2)

    def feature_box(self, text: str):
        self.set_fill_color(240, 250, 245)
        self.set_draw_color(*GREEN)
        self.set_line_width(1)
        self.set_x(self.l_margin + 4)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(26, 26, 26)
        self.multi_cell(self.epw - 8, 5.5, _safe(text), border=0, fill=True)
        self.ln(2)

    def bullet(self, text: str, indent: float = 4):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(26, 26, 26)
        self.set_x(self.l_margin + indent)
        self.cell(4, 5.5, "-", ln=False)
        self.set_x(self.l_margin + indent + 4)
        self.multi_cell(self.epw - indent - 4, 5.5, _safe(text))

    def change_block(self, label: str, text: str):
        self.set_fill_color(250, 250, 250)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*GRAY)
        self.set_x(self.l_margin + 2)
        self.cell(0, 5, label.upper(), ln=True)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(26, 26, 26)
        self.set_x(self.l_margin + 2)
        self.multi_cell(self.epw - 2, 5.5, _safe(text))
        self.ln(2)

    def task_row(self, num: int, title: str, estimate: str, desc: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(26, 26, 26)
        self.set_x(self.l_margin)
        self.cell(6, 6, str(num), ln=False)
        self.cell(self.epw - 20, 6, _safe(title), ln=False)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GRAY)
        self.cell(14, 6, _safe(estimate), align="R", ln=True)
        self.set_font("Helvetica", "", 9.5)
        self.set_text_color(*GRAY)
        self.set_x(self.l_margin + 6)
        self.multi_cell(self.epw - 6, 5, _safe(desc))
        self.ln(1)


AMBER = (180, 120, 20)


def _strip_inline(text: str) -> str:
    """Remove inline markdown markers (*bold*, _italic_, `code`) for plain PDF text."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"__(.+?)__", r"\1", text)
    text = re.sub(r"_(.+?)_", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    return text.strip()


def render_markdown_block(pdf: "PRDPdf", content: str) -> None:
    """Render markdown prose into the PDF — handles headings, bullets, and paragraphs."""
    lines = content.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()

        # Skip blank lines (add small spacing)
        if not line:
            pdf.ln(1)
            i += 1
            continue

        # ATX headings ## and ###
        if line.startswith("### "):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*GRAY)
            pdf.cell(0, 5, _safe(_strip_inline(line[4:])), ln=True)
            pdf.ln(1)
        elif line.startswith("## "):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(26, 26, 26)
            pdf.cell(0, 6, _safe(_strip_inline(line[3:])), ln=True)
            pdf.ln(1)
        # Bullet: - item or * item
        elif re.match(r"^[-*]\s+", line):
            text = re.sub(r"^[-*]\s+", "", line)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(26, 26, 26)
            pdf.set_x(pdf.l_margin + 4)
            pdf.cell(4, 5.5, "-", ln=False)
            pdf.set_x(pdf.l_margin + 8)
            pdf.multi_cell(pdf.epw - 8, 5.5, _safe(_strip_inline(text)))
        # Numbered list: 1. item
        elif re.match(r"^\d+\.\s+", line):
            text = re.sub(r"^\d+\.\s+", "", line)
            num = re.match(r"^(\d+)\.", line).group(1)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(26, 26, 26)
            pdf.set_x(pdf.l_margin + 4)
            pdf.cell(6, 5.5, f"{num}.", ln=False)
            pdf.set_x(pdf.l_margin + 10)
            pdf.multi_cell(pdf.epw - 10, 5.5, _safe(_strip_inline(text)))
        # Plain paragraph
        else:
            # Collect consecutive non-blank, non-special lines into one paragraph
            para_lines = []
            while i < len(lines) and lines[i].rstrip() and not re.match(r"^(#{1,3}\s|[-*]\s|\d+\.\s)", lines[i]):
                para_lines.append(lines[i].rstrip())
                i += 1
            para = " ".join(para_lines)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(26, 26, 26)
            pdf.multi_cell(pdf.epw, 5.5, _safe(_strip_inline(para)))
            pdf.ln(1)
            continue  # i already advanced

        i += 1


def generate_pdf(brief: dict, output_path: str, extensions: list[dict] | None = None) -> None:
    pdf = PRDPdf(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()
    pdf.set_margins(18, 18, 18)

    # ── Title block ──────────────────────────
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*PURPLE)
    pdf.cell(0, 10, "PRD", ln=True)
    pdf.set_draw_color(*PURPLE)
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + pdf.epw, pdf.get_y())
    pdf.ln(6)

    # ── Problem ──────────────────────────────
    pdf.section_title("Problem")
    pdf.body_text(brief.get("problem", ""))
    for q in brief.get("problem_quotes", []):
        pdf.quote_block(q)
    pdf.ln(2)

    # ── Proposed Feature ─────────────────────
    pdf.section_title("Proposed Feature")
    pdf.feature_box(brief.get("proposed_feature", ""))
    pdf.ln(2)

    # ── Why Build ────────────────────────────
    pdf.section_title("Why It's Worth Building")
    pdf.body_text(brief.get("why_worth_building", ""))

    # ── Goals / Non-Goals ────────────────────
    goals = brief.get("goals", [])
    non_goals = brief.get("non_goals", [])
    if goals or non_goals:
        pdf.section_title("Goals & Non-Goals")
        if goals:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*GRAY)
            pdf.cell(0, 5, "GOALS", ln=True)
            for g in goals:
                pdf.bullet(g)
            pdf.ln(2)
        if non_goals:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*GRAY)
            pdf.cell(0, 5, "NON-GOALS", ln=True)
            for g in non_goals:
                pdf.bullet(g)
            pdf.ln(2)

    # ── User Stories ─────────────────────────
    stories = brief.get("user_stories", [])
    if stories:
        pdf.section_title("User Stories")
        for s in stories:
            pdf.bullet(s)
        pdf.ln(2)

    # ── What Needs to Change ─────────────────
    wtc = brief.get("what_needs_to_change", {})
    if any(wtc.get(k) for k in ("ui", "data_model", "workflows")):
        pdf.section_title("What Needs to Change")
        if wtc.get("ui"):
            pdf.change_block("UI Changes", wtc["ui"])
        if wtc.get("data_model"):
            pdf.change_block("Data Model", wtc["data_model"])
        if wtc.get("workflows"):
            pdf.change_block("Workflows", wtc["workflows"])

    # ── Engineering Tasks ────────────────────
    tasks = brief.get("engineering_tasks", [])
    if tasks:
        pdf.section_title("Engineering Tasks")
        for i, t in enumerate(tasks, 1):
            pdf.task_row(i, t.get("title", ""), t.get("estimate", "M"), t.get("description", ""))

    # ── Edge Cases ───────────────────────────
    edge_cases = brief.get("edge_cases", [])
    if edge_cases:
        pdf.section_title("Edge Cases")
        for c in edge_cases:
            pdf.bullet(c)
        pdf.ln(2)

    # ── Analytics Events ─────────────────────
    events = brief.get("analytics_events", [])
    if events:
        pdf.section_title("Analytics Events")
        for e in events:
            pdf.bullet(e)
        pdf.ln(2)

    # ── Open Questions ───────────────────────
    questions = brief.get("open_questions", [])
    if questions:
        pdf.section_title("Open Questions")
        for q in questions:
            pdf.bullet(q)

    # ── Extensions ───────────────────────────
    for ext in (extensions or []):
        pdf.ln(6)
        pdf.set_draw_color(*AMBER)
        pdf.set_line_width(0.4)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + pdf.epw, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*AMBER)
        label = f"{ext.get('label', 'Update')} — {ext.get('date', '')}"
        pdf.cell(0, 7, _safe(label.upper()), ln=True)
        pdf.set_draw_color(*AMBER)
        pdf.set_line_width(0.3)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + pdf.epw, pdf.get_y())
        pdf.ln(2)
        render_markdown_block(pdf, ext.get("content", ""))

    pdf.output(output_path)
